object Versions {
    const val coreVersion = "1.12.0"
    const val runtimeKtx = "2.7.0"
    const val activityCompose = "1.8.2"
    const val composeBom = "2023.08.00"
    const val junitVersion = "4.13.2"
    const val extJUnitVersion = "1.1.5"
    const val espressoCoreVersion = "3.5.1"
    const val composeBomVersion = "2023.08.00"
    const val nav_version = "2.7.6"
    const val room_version = "2.6.1"
    const val hilt_version = "2.48"
    const val retrofit_version = "2.9.0"
    const val runtime_compose = "2.6.2"
}