object Versions {
    const val coreVersion = "1.12.0"
    const val runtimeKtx = "2.7.0"
    const val activityCompose = "1.8.2"
    const val composeBom = "2023.08.00"
    const val junitVersion = "4.13.2"
    const val extJUnitVersion = "1.1.5"
    const val espressoCoreVersion = "3.5.1"
    const val composeBomVersion = "2023.08.00"
    const val nav_version = "2.7.6"
    const val room_version = "2.6.1"
    const val hilt_version = "2.48"
    const val retrofit_version = "2.9.0"
    const val runtime_compose = "2.6.2"

    // test version
    const val roomTestingVersion = "2.5.1"
    const val mockServerVersion = "4.11.0"
    const val coroutineVersion = "1.5.2"
    const val mockitoTestVersion = "4.0.0"
    const val mockitoKotlinTestVersion = "2.2.0"
    const val coreTestingVersion = "2.1.0"
    const val turbineVersion = "1.1.0"
    const val mockitoInlineVersion = "3.6.0"
}